server:
  port: 13600

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.100.5:3306/project?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    password: admin
    username: root

  freemarker:
    check-template-location: false

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

file-path: D:/project/
